version: '3.7'
services:
  db:
    image: mysql
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=taxiDB
      - MYSQL_PASSWORD=password
    ports:
      - 3308:3306

  service:
    image: andrewmereuta/taxi-project
    container_name: service
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=taxiDB
      - DATABASE_PORT=3306